# Configuration File
title: Colin Rubbert - Designer Developer Creative
email: colinrubbert@gmail.com
description: Colin Rubbert is a designer, developer, creative, terribly sporadic writer, and was the kid who day dreamed while staring out the window during class. Always open for a good conversation or adventure, currently for hire.
baseurl: "/"
url: "http://colinrubbert.com"
twitter_username: colinrubbert
github_username:  colinrubbert
instagram_username:  colinrubbert
host: 0.0.0.0

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
gems:
  - jekyll-paginate # Manually add to Gemfile in Jekyll Plugins
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Pagination Settings
paginate: 10
paginate_path: "/articles/page:num"
