# Configuration File
title: Colin Rubbert - Designer Developer Creative
email: colinrubbert@gmail.com
description: Colin Rubbert is a designer, developer, creative, terribly sporadic writer, and was the kid who day dreamed while staring out the window during class. Always open for a good conversation or adventure, currently for hire.
baseurl: "/"
url: "http://colinrubbert.com"
twitter_username: colinrubbert
github_username:  colinrubbert

# Build settings
sass:
  style: :nested
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
